# Copyright (c) 2026 Kirky.X. All rights reserved.
# See LICENSE for full license text.

[toolchain]
channel = "stable"
components = ["rustfmt", "clippy", "rust-docs"]
profile = "default"
targets = ["x86_64-unknown-linux-gnu"]
