# Copyright (c) 2026 Kirky.X🌠
# SPDX-License-Identifier: Apache-2.0

[toolchain]
channel = "stable"
components = ["rustfmt", "clippy", "rust-docs"]
profile = "default"
targets = ["x86_64-unknown-linux-gnu"]
